### ISSUE TITLE
When running in Azure An Exception is thrown in ConnectionFactory.CreateAsync()

### ISSUE THREAD

**Issue by matlus** [ppatierno/azuresblite-examples#1]
I made a simple ASP.NET application that uses the AzureSBLite library to talk to a ServiceBus Topic (send messages only).

This application works as expected when I run it on my local machine. However, when deployed to Azure, I get an exception when attempting to create a connection. The Exception message and stack trace is below:
An address incompatible with the requested protocol was used

   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Amqp.TcpTransport.<ConnectAsync>b__1(IAsyncResult r) in d:\Source\Repos\amqpnetlite-git\src\Net\TcpTransport.cs:line 75
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amqp.TcpTransport.<ConnectAsync>d__5.MoveNext() in d:\Source\Repos\amqpnetlite-git\src\Net\TcpTransport.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amqp.ConnectionFactory.<CreateAsync>d__0.MoveNext() in d:\Source\Repos\amqpnetlite-git\src\Net\ConnectionFactory.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IoTCommandCenter.Handlers.LightsHandler.<ProcessRequestAsync>d__10.MoveNext() in C:\Users\Shiv\OneDrive\Projects\C#\Iot\RasberryPi2\IoTController\IoTCommandCenter\Handlers\LightsHandler.cs:line 50

What do you think is the problem here?

**Comment by matlus** [comment]
I think this may have something to do with the application (the ASP.NET) application in this case running in localhost (or a non routable IP address) and possibly a combination is an IPv4 versus IPv6 address.

I do get this error if I use the wrong protocol constructor of the Address class like so
`address = new Address(servicebusEntityName, 5671, null, null, "/", "xxxx");`

Of course what I really have is `amqps` in my actual code that is deployed to Azure
